import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { parseKeyFile, SystemKeyParseError } from "../src/lib/system-keys/format";
import { getSystem, SYSTEMS } from "../src/lib/coupon-systems";
import { validateSystemKey } from "../src/lib/system-keys/index";

interface FileResult {
  code: string;
  rows: readonly string[];
  problems: string[];
}

const keysDir = join(process.cwd(), "system-keys");
const outputFile = join(
  process.cwd(),
  "src/lib/system-keys/generated-keys.ts"
);

/**
 * Load all .txt files from the system-keys directory.
 */
function loadKeyFiles(): FileResult[] {
  const results: FileResult[] = [];

  // Get all system codes from the catalogue
  const systemCodes = SYSTEMS.map((s) => s.code);

  // Try to load each system code's file
  for (const code of systemCodes) {
    // Skip M-type systems (generated, not file-backed)
    const system = getSystem(code);
    if (!system) continue;

    if (system.type === "M") {
      // M-type systems are generated, not loaded from file
      continue;
    }

    const filename = `${code.toLowerCase()}.txt`;
    const filePath = join(keysDir, filename);

    try {
      const content = readFileSync(filePath, "utf-8");
      const rows = parseKeyFile(content);
      const problems = validateSystemKey(system, rows);

      results.push({
        code,
        rows,
        problems,
      });

      // Log validation status
      if (problems.length === 0) {
        console.log(`✓ ${code}: ${rows.length} rows, ${rows[0]?.length || 0} columns`);
      } else {
        console.log(`✗ ${code}: INVALID`);
        for (const problem of problems) {
          console.log(`    ${problem}`);
        }
      }
    } catch (error) {
      const message =
        error instanceof SystemKeyParseError
          ? error.message
          : error instanceof Error
            ? error.message
            : String(error);

      results.push({
        code,
        rows: [],
        problems: [`Failed to parse: ${message}`],
      });

      console.log(`✗ ${code}: PARSE ERROR`);
      console.log(`    ${message}`);
    }
  }

  return results;
}

/**
 * Check for any validation problems and exit if found.
 */
function checkProblems(results: FileResult[]): void {
  const hasProblems = results.some((r) => r.problems.length > 0);

  if (hasProblems) {
    const total = results.filter((r) => r.problems.length > 0).length;
    console.error(`\n❌ ${total} file(s) failed validation.`);
    process.exit(1);
  }
}

/**
 * Generate the TypeScript module.
 */
function generateModule(results: FileResult[]): string {
  // Sort by code for stable output
  const sorted = results.sort((a, b) => a.code.localeCompare(b.code));

  const entries = sorted
    .map((result) => {
      const rowsCode = result.rows
        .map((row) => `"${row}"`)
        .join(",\n    ");
      return `  "${result.code}": [\n    ${rowsCode},\n  ] as const,`;
    })
    .join("\n");

  return `/**
 * GENERATED by scripts/generate-system-keys.ts — do not edit by hand.
 * Run \`npm run keys:generate\` after changing anything in system-keys/.
 */
export const FILE_SYSTEM_KEYS: Record<string, readonly string[]> = {
${entries}
};
`;
}

/**
 * Main entry point.
 */
async function main() {
  console.log("Generating system keys...\n");

  const results = loadKeyFiles();

  checkProblems(results);

  const module = generateModule(results);
  writeFileSync(outputFile, module, "utf-8");

  console.log(`\n✓ Generated ${outputFile}`);
  console.log(`✓ All ${results.length} keys validated successfully.`);
}

main().catch((error) => {
  console.error(
    `Fatal error: ${error instanceof Error ? error.message : String(error)}`
  );
  process.exit(1);
});
